### ISSUE TITLE
Can we add the ability to create every new user in `GOOGLE_SSO_ALLOWABLE_DOMAINS` as a superuser?

### ISSUE THREAD

**Issue by willbeaufoy** [chrismaille/django-google-sso#10]
E.g. a setting called `GOOGLE_SSO_AUTO_CREATE_SUPERUSERS`, so any new auto created user will be a superuser.

I can do a PR for this myself if needed.

**Comment by chrismaille** [comment]
hi @willbeaufoy,

Can you check on the new version 2.4.0  I've upload today, this configuration can help you: `GOOGLE_SSO_PRE_LOGIN_CALLBACK`?

Using this option you can set a callable which will receive two objects - user and request, to be processed after user is retrieved/created but before login.

For example:

```python
# my_app/hooks.py
from django.contrib import messages
from loguru import logger

def pre_login_callback(user, request):
    """Callback function called after user is logged in."""
    messages.info(request, f"Running Pre-Login callback for user: {user}.")
    if not user.is_superuser or not user.is_staff:
        logger.info(f"Adding SuperUser status to email: {user.email}")
        user.is_superuser = True
        user.is_staff = True
        user.save()

# settings.py
GOOGLE_SSO_PRE_LOGIN_CALLBACK = "my_app.hooks.pre_login_callback"
```
