### ISSUE TITLE
AttributeError: 'UserManager' object has no attribute 'find' with GOOGLE_SSO_AUTO_CREATE_USERS = False

### ISSUE THREAD

**Issue by blueyed** [chrismaille/django-google-sso#12]
UserManager has no method `find`.  This is used with `GOOGLE_SSO_AUTO_CREATE_USERS = False` via `django_google_sso/views.py(98)callback()`.

https://github.com/chrismaille/django-google-sso/blob/79ba9869ddb2dcf66ae62174ad3e71da046427dc/django_google_sso/main.py#L152

Maybe `filter` was meant to be used there?

The following patch fixes it, using a single query always:
```diff
diff --git i/django_google_sso/main.py w/django_google_sso/main.py
index c749c7a..d4b75a2 100644
--- i/django_google_sso/main.py
+++ w/django_google_sso/main.py
@@ -149,6 +149,7 @@ def check_for_permissions(self, user):

     def find_user(self):
         user_model = get_user_model()
-        query = user_model.objects.find(email=self.user_email)
-        if query.exists():
-            return query.get()
+        try:
+            return user_model.objects.get(email=self.user_email)
+        except user_model.DoesNotExist:
+            return None
```

Note that there is no user message in case a user is not found (and not auto-created) - should there be a hint in this case?

**Comment by chrismaille** [comment]
Good catch. It is indeed a typo - `find` did not exists in default django Manager. 👍🏾
