### ISSUE TITLE
State Mismatch. Time expired?

### ISSUE THREAD

**Issue by astopienski** [chrismaille/django-google-sso#3]
Hey there. First of all, thanks for creating such a usefull package!
I'm experiencing a following problem. I have 2 Django projects that use Google SSO login and are running on CloudRun. The settings in settings.py file are the same in the "Google" part. I checked every line of code to make sure that I did everything right. Login in the 1st project works perfect. In the 2nd project I get an error "State Mismatch. Time expired?" after I log in with my google account. If I try to log in 2-3 times in a row, I get through, but not on the home page - I land on Django admin. I inspected the login process with the browser dev tools - when I open home page after login, there's no "sessionid" in request cookies.
The 1st project has django-google-sso in 2.0.0 version. The 2nd - in 2.2.0. This is the only difference between projects. I thought it could have probably something to do with it. Do you have an idea where could be a problem?
![Screenshot (42)](https://user-images.githubusercontent.com/115219708/194521589-503d34ac-b44a-4d44-baae-8601df4e722e.png)

**Comment by chrismaille** [comment]
Hi @astopienski. Got this error too. I'm believing this is because i've started using Django Caching system to store the state between the requests on version 2.2. I'm still debugging this, but in the next version, i`ll add a option to mak cache system optional.

Thanks for the issue.

**Comment by gasci** [comment]
Hi, I am having the same problem, too. Could you find a solution?

**Comment by chrismaille** [comment]
Hi @gasci. Yes, I found  and I'm working on it. The next release will be release on the next days.
