### ISSUE TITLE
ValueError at /google_sso/callback/: multiple authentication backends

### ISSUE THREAD

**Issue by savionak** [chrismaille/django-google-sso#4]
Hi there, thanks for creating this awesome library!

I faced the following error when trying to log in with Google:
```
ValueError at /google_sso/callback/
You have multiple authentication backends configured and therefore must provide the `backend` argument
or set the `backend` attribute on the user
```

The error occurs at [views.py#L87](https://github.com/chrismaille/django-google-sso/blob/c6054e3a9979aef73c32e567772572ab34e972a8/django_google_sso/views.py#L87):
```
86  # Login User
87  login(request, user)
```

Indeed, my project has two authentication backends: `django.contrib.auth.backends.ModelBackend` for default auth methods and `social_core.backends.auth0.Auth0OAuth2` for OAuth2 integration, and both are essential.

Maybe there could be a way to specify which authentication backend to use during login?

**Comment by savionak** [comment]
I tried to add a `GOOGLE_SSO_AUTHENTICATION_BACKEND` to fix this error and it helped. Maybe you'll come up with a different approach, but please take a look.

**Comment by chrismaille** [comment]
Hi @savionak 

Thanks for the contribution. You got a good catch here, can I ask you please change PR target to my `develop` branch, so I can add some tests, before going live?

Thank you again.
